name: eShopOnWeb Build and Test
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE_GROUP: rg-az400-eshoponweb-NAME
  LOCATION: westeurope
  TEMPLATE_FILE: .azure/bicep/webapp.bicep
  SUBSCRIPTION_ID: YOUR-SUBS-ID
  WEBAPP_NAME: az400-webapp-NAME

jobs:
  # Build, test and publish .NET web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Prepare runner for desired .NET version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      # Build/Test/Publish the .NET project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/Web/Web.csproj -c Release -o ./myapp

      # Upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ./myapp

      # Upload the Bicep template as artifacts for next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

  # Use Bicep to deploy infrastructure + publish web app 
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      # Download the publish files created in previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: .net-app

      # Download the Bicep templates from previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: bicep-template
          path: bicep-template

      # Login to your Azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure Web App using Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: bicep-template/webapp.bicep
          parameters: 'webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false

      # Publish website to Azure App Service (WebApp)
      - name: Publish Website to WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: .net-app

   
